#!/usr/bin/env python

try:
  import configparser
except ImportError:
  import ConfigParser as configparser
import irc_connection
import brain

if __name__ == "__main__":

  config = configparser.ConfigParser()

  # Setting default values

  config.set('DEFAULT', 'nick', 'marvin')
  config.set('DEFAULT', 'fullname', 'Marvin the Paranoid Android')
  config.set('DEFAULT', 'password', '')
  config.set('DEFAULT', 'servname', 'unknown')
  
  config.set('DEFAULT', 'host', 'irc.oftc.net')
  config.set('DEFAULT', 'port', '6667')
  config.set('DEFAULT', 'channels', '')

  config.set('DEFAULT', 'debug', '')

  config.read('marvin.conf')

  connections = []

  for section in config.sections():

    channels = config.get(section, 'channels').split()
    debug = False if (config.get(section, 'debug') == "") else True
    password = None if (config.get(section, 'password') == "") else config[section]['password']
    connections.append(irc_connection.IrcConnection( 
      section, 
      channels=channels, 
      debug=debug,
      port=int(config.get(section, 'port')),
      nick=config.get(section, 'nick'),
      password=password,
      fullname=config.get(section, 'fullname'),
      servname=config.get(section, 'servname')))

  while True:
    for connection in connections:
      response = connection.getNextChat()
      print((connection.host, response[0], response[1], response[2]))

      # Sender, message
      res = brain.think(response[0], response[2])

      if res:
        connection.sendChat(response[1], res)
